### ISSUE TITLE
Missdirecting the realm URL

### ISSUE THREAD

**Issue by AaronShea** [defaye/discourse-steam-login#2]
Hello there, I'm interested in your plugin here for discourse but I'm running into a very strange issue, when I hit sign up or login with steam buttons, I am directed to the login page like usually, however once I put in my steam credentials and authorize the login, it redirects me to a URL starting with:

`http://discourse`

and not the proper domain name of my forum

I've tried to override the realm URL manually, and that fixed the redirection, however now I end up with an error in the popup window:

```
Sorry, there was an error authorizing your Steam account. Perhaps you did not approve authorization?
```

Any idea on why this could be happening?

**Comment by defaye** [comment]
Did you figure out what the problem was? I have not been able to look at my plugin for a while. But it works for me on a fresh Discourse Docker install from the instructions provided for install so I can only assume there was a configuration mistake in your install. I'm not sure what exactly the referenced changes have to do with this but I will take a look at them.
